### ISSUE TITLE
Admin: Create Navigation

### ISSUE THREAD

**Issue by edgilmore** [GreenLightSolutionsFoundation/gls-dashboard#29]
Create a navigation component for the admin section of the applicaiton

**Comment by w33ble** [comment]
@edgilmore this is done isn't it?

**Comment by edgilmore** [comment]
Yes

Sent from my iPhone

On Jul 21, 2017, at 5:45 PM, Joe Fleming <notifications@github.com<mailto:notifications@github.com>> wrote:


@edgilmore<https://github.com/edgilmore> this is done isn't it?
